export default {
	DO_LOGIN: 'DO_LOGIN',
	DO_LOGOUT: 'DO_LOGOUT',
	GET_HOSPITAL: 'GET_HOSPITAL',
	GET_LIST_HOSPITAL: 'GET_LIST_HOSPITAL',
	GET_LIST_AREA: 'GET_LIST_AREA',
	LIST_TYPE: 'LIST_TYPE',
	GET_NOTIFICATION: 'GET_NOTIFICATION',
	UPDATE_PROFILE: 'UPDATE_PROFILE',
	GET_LIST_MEDICALS: 'GET_LIST_MEDICALS',
	GET_LIST_COURSES: 'GET_LIST_COURSES',
	GET_LIST_ROOM: 'GET_LIST_ROOM',
	GET_LIST_TYPES: 'GET_LIST_TYPES'
};